apiVersion: v1
kind: Secret
metadata:
  name: lgr-secrets
  namespace: {{ the namespace used }}
  labels:
    env: {{ the environement used }}
    app: lgr
type: Opaque

stringData:
  lgrSecretKey: {{ Randomly generated secret key }}
  lgrRedisPwd: {{ the icann sentry redis instance password }}
